version: '3.3'
services:
  master:
    image: crawlabteam/crawlab:0.6.0
    container_name: crawlab_master
    environment:
      CRAWLAB_NODE_MASTER: "Y"
      CRAWLAB_MONGO_HOST: "mongo"
      CRAWLAB_REDIS_ADDRESS: "redis"
      CRAWLAB_LOG_LEVEL: "info"
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - redis
    volumes:
      - "./crawler-project:/app/crawler-project"  # 挂载爬虫项目目录
    restart: unless-stopped

  worker:
    image: crawlabteam/crawlab:0.6.0
    container_name: crawlab_worker
    environment:
      CRAWLAB_NODE_MASTER: "N"
      CRAWLAB_GRPC_ADDRESS: "master"
      CRAWLAB_FS_FILER_URL: "http://master:8080/api/filer"
      CRAWLAB_MONGO_HOST: "mongo"
      CRAWLAB_REDIS_ADDRESS: "redis"
      CRAWLAB_LOG_LEVEL: "info"
    depends_on:
      - master
    volumes:
      - "./crawler-project:/app/crawler-project"  # 挂载爬虫项目目录
    restart: unless-stopped

  mongo:
    image: mongo:4.4
    container_name: crawlab_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - crawlab_mongo:/data/db

  redis:
    image: redis:6.2-alpine
    container_name: crawlab_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - crawlab_redis:/data

volumes:
  crawlab_mongo:
  crawlab_redis: